language: python
sudo: false
# TODO Implement mac os x testing
matrix:
    include:
        - os: linux
          dist: xenial
          python: 3.5
        - os: linux
          dist: xenial
          python: 3.6
        - os: linux
          dist: xenial
          python: 3.7

# TODO Use a conda setup script like in my other repo
before_install:
- pip install --upgrade pip setuptools wheel pytest
- pip install --only-binary=numpy,scipy numpy scipy
- pip install spiceypy --no-cache-dir
- pip install twine
- pip install -r requirements.txt
install:
- python setup.py install
script:
- py.test --cov=astro
after_success:
- coveralls
deploy:
  provider: pypi
  user: skulumani
  password:
    secure: u3QpDzRUyFQDStc+ZLNKNHafSj+DFnjPxjbaylljdcU12a97FBgR9iK+QAODt0qsF86i3hIZwPgvLJ0ibD4s/EFfKgQPSpYPPzQsnQOYu6szjU8b1V4TT8JaRCW3qofFC6IRVxxWAdECx1MebtpeDO7Ab7U+M3fFMXjQbM3vOYZHiM5ynB3nvRfxFuLg44M9cU0hQdhVYWz3L9CylNgHsXBDL1VLufjY+5uXZmq/UnvXNjXuuv0D7bNM+opCkr8gzAvtZhr94G6AbAmRRfSWFJtHQuV8yNIf9jOC7vR5JhBJ8mos9ljVZIYevA4rf+ejB58AUP8dwBso1zMArgW+bAgjQjSsYIILDtc8CX4TPPLKJIcpwdFfhSICa2EzmCFba8fUwWQH9k9vXyx8IFMbMoyvDoG5yrlRGMtKTjJDrPJVHoS18t+YBlrqCN71ylMmTd98Isc8ERM89bPRcBnU8BD5sBu82wSkCeS7FozhgGZ9L14q91R8nQ0sf3dkLUcHPRq4rDYTKOlkW48qWxmXbdd6FJCH/HY9RBVCj1Xxqfnkt5AWoC0MIw62JccTXBvyQizgHeEsENz17K5Gg6yTkpIW8zHaX6+VlXmP791F6xaMgv+WebpAO/TKw6VmUOB9Mm6RmEF30T81ne4WWv1+m8ZNTEJz7RozLlDi75JX0AM=
  on:
    tags: true
    branch: master
    # distributions: sdist bdist_wheel
    # python: '3.6'
