name: astro
channels:
- defaults
- skulumani
- conda-forge
dependencies:
- python=3
- numpy>=1.12
- pip
- matplotlib
- ipython
- scipy
- pytest
- pytest-cov
- coverage
- kinematics
- spiceypy
- pip:
    - spacetrack

