name: astro
channels:
- defaults
dependencies:
- python=3
- numpy>=1.12
- pip
- matplotlib
- ipython
- scipy
- pytest
- pytest-cov
- coverage
- pip:
    - kinematics
    - spacetrack
    - spiceypy
    - sphinx
    - sphinx-autobuild
    - twine

